.TH myBash 1
.SH NAME
myBash \- Creates a lot of files
.SH SYNOPSIS
.B myBash
[ f ]
[ n ]
.SH DESCRIPTION
.B myBash
The program creates a number of folders with -f as a count. it uses -n as a name with a number generated on the right of the name 
.SH OPTIONS
.TP
.BR f
Number of folders to generate
.TP
.BR n
The name of the folders
